spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 表示使用小写的 service id 作为第一重映射
#          route-id-prefix: /api/v1/
      routes:
        - id: fsh-house
          uri: lb://login-service
          predicates:
            - Path=/example/**
            - Path=/example/**

  application:
    name: gateway

eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:8100/eureka/ #配置注册中心地址