spring:
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true # 表示使用小写的 service id 作为第一重映射
#          route-id-prefix: /api/v1/
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins:
              - "localhost://8081"
              - "localhost://8080"
              - "http://*.guisu.website"
              - "https://*.guisu.website"
            allowedMethods:
              - GET
                POST
                DELETE
                PUT
                OPTION
      routes:                          # Add your services here
        - id: login-service            # Only for identifying your rules
          uri: lb://login-service      # Use this pattern: lb://<service-name-of-eureka>
          predicates:                  # Pattern /api/{segment}/<locator-of-your-apis>/**, locator 请见飞书文档
            - Path=/api/{segment}/login/**
        - id: stayInformation-service
          uri: lb://stayInformation-service
          predicates: # Pattern /api/{segment}/<locator-of-your-apis>/**, locator 请见飞书文档
            - Path=/api/{segment}/stay/**
        - id: statistics-service
          uri: lb://statistics-service
          predicates:
            - Path=/api/{segment}/statistics/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/{segment}/order/**,/api/{segment}/orders/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/{segment}/payment/**
        - id: trade-service
          uri: lb://trade-service
          predicates: 
            - Path=/api/{segment}/trade/**
        - id: personalInformartion-service
          uri: lb://PERSONALINFORMARTION-SERVICE
          predicates:
            - Path=/api/{segment}/personinfo/**
        - id: sale-service
          uri: lb://SALE-SERVICE
          predicates:
            - Path=/api/{segment}/sale/**

  application:
    name: gateway

eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:8100/eureka/ #配置注册中心地址