server:
  port: 8088 #运行端口号
spring:
  application:
    name: payment-service #服务名称
eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://8.131.225.65:8100/eureka/ #配置注册中心地址
  instance:
    prefer-ip-address: true
    instance-id: 121.5.140.125:${spring.application.name}:${server.port}
    ip-address: 121.5.140.125