spring:
  application:
    name: login-service #服务名称
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 121.5.140.125
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ENC(LvfQLvutAb64FW8NX8MK1ElIJB8v8tEi)
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
          # 连接池中的最大空闲连接
        max-idle: 10
          # 连接池中的最小空闲连接
        min-idle: 0

eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:8100/eureka/ #配置注册中心地址

sa-token:
  # -------------- SSO-模式一相关配置  (非模式一不需要配置)
  # cookie:
  # 配置Cookie作用域
  # domain: stp.com

  # ------- SSO-模式二相关配置
  sso:
    # Ticket有效期 (单位: 秒)，默认五分钟
    ticket-timeout: 300
    # 所有允许的授权回调地址
    allow-url: "*"
    # 是否打开单点注销功能
    is-slo: true
